name: Download TW CDC reports

on:
  workflow_dispatch:
  schedule:
    - cron: '9,19,29,39,49,59 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Display Python version
        run: 
          python -c "import sys; print(sys.version)"
          python --version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4

      - name: Download TW CDC reports
        run: |
          python src/download_tw_cdc_reports.py
          
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Add new CDC reports'
          add: '*.pdf'


