name: Download TW CDC reports

on:
  schedule:
    - cron: '9/20 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Display Python version
        run: 
          python -c "import sys; print(sys.version)"
          python --version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4

      - name: Download TW CDC reports
        run: |
          python src/download_tw_cdc_reports.py
          
      - name: Get current time in TW
        run: echo "TIMESTAMP=$(TZ=':Asia/Taipei' date +'%Y/%m/%d %H:%M')" >> $GITHUB_ENV
        
      - name: Echo current time
        run: echo $TIMESTAMP
        
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'latest TW CDC reports ($TIMESTAMP)'
          add: '*.pdf'


